# Generated by Django 3.2.7 on 2022-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
